name: Calendar Reminder

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Set up Google Cloud credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/credentials.json

      - name: Run script
        run: python your_script.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/credentials.json
