name: Calendar Notifier

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Run script
      env:
        SERVICE_ACCOUNT_JSON: '{
          "type": "service_account",
          "project_id": "inte-428705",
          "private_key_id": "d6b9c48b1645fd782291ea2b6b34ada3f14961a5",
          "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDFuJQC1ELhN7Pd\n/SJbeMRjk7Trh5WyWZ7YZ5Kg9tDPzkGiwQS6mBBs5GXVRSDa//seqnzvEwlTqhch\nfdz7h7dTRLdD/b4Us4lUnZvSNqEmXjlY7BOIklAwNXHJ0jvmg46E7Lf+z0Fj7Zdo\nKQvBt+COIdfDInDKVswAMVXQRCkHGv3vDOVMe3w0bI16Bu6nHILSPjVUifYmGpin\nn40KHX+v681Rb48uUMd2BDR2ujMz9FnRh3McwRF8ewQPDuslBy/T6KlU1VZQNPHy\n1PFOPekZa9zP6uzknzssByaz8pTyGoJvQz7jGLky8FscLpdQpmS1VqK1E8Qu5lZ1\nOwB1fywZAgMBAAECggEABAvfw5PyfY6RuMgWpgaV6eGQFmpU7vOUlWlqHD1tTwNq\nmDynPOZbHs9hzM2qJeodNTTmczPfwRoFP9T/B1Hi8HiJ4A/I//c8NUKM63yH1jO8\nHkWlrZSeT0cm8qszjmdc122SHC+nNiio85VQy7lYaekggg+4RFEmpaOyKx2/UaXC\npP+c592GYeA4LClWnBrRFgB9182wiQ/qedU6wnCjf+sLyjz7nsn2e3Ae+rX1Av1H\nqVIoEaMJKieqCsTXjRhguB97C44XIJUX56zTesIa8atCkZt0z8klybbzSTdsD0I9\nOQr4BKAftVzJ10sLTE2DNAfTg0vEWr2Cw5KUgo9cjQKBgQDyPHIqv3qCKbpJGbOc\n4effigDft+v2LSR9ytCnJwyKhHRNmX5+Cc7oFDxGr6QbQrbVQmRb0GCdGJGFgigw\n97FbrmFBYHDYb+Pg50bWeV4dvA3ra6iksDsz/lIKARX4+fA9hkrAy0FWwt8MKIEN\nDZbaxRrgw85Av0i0L1x35QUUnwKBgQDQ9J4j56uGgn2etnAZhwGjkkA0tFpoztHt\ne7YT6FA7c88ECy71EIY1+2FfcQQI9WeumwxYbLhQcvBOjyZ1mlYDN5+dU/jAuOQ9\nqxF6qhI4SfcaY/p6JTa0Ee7GsLDOBGic+Y+hGZMS6+lVzsF3+mrj99dngpOlcP+w\nBVpZsIEMRwKBgQDHQr3POE94PwcEFuZPCO2KTqVFYq/xg1TfPTTCKzb/wtFA/CC3\nYS4Ybnze0KC34/suFj0j4Zd34rviDR0umrIEbr+F3eU1xWS4nscAqjmnUAhLPfYt\n8uHgdTXbEOWYN1FN6ugXC5ul2QtNnwv5RtJvB3CCr888J52QytzPq06wlQKBgFha\nRo/KApXykSlN3OJ+WmwOiAWBCQVuBgfTmm6aeWpaEnuUOvu2S/mBXG/duqYLFhcX\nSkYNWnXx07h0AQATDTF5EI2WlwTuaNvGfLKQPPn+FHTdN2j0WUgUmRD8XxYNeSp+\nv4OP68dBZz04Gkgf45iXEEadSM7Yk9SavtRTtI07AoGAVQi/y/bnkYaLrlZ1WNNk\nVlrjlDTYAJtRhcwr0ZvYzoUgdP5bm9m9fci6PSwq/2rBFs+l+a99AD4QaEUaTUQh\nOyP1VOs8jD6cZqO+hw8GMXQam1ImJWfz0zaY/YTwLaq7amfSP39hBGhQ/VIL4CP0\nTDrX9Rn0D1aGGIjG7hg8NK8=\n-----END PRIVATE KEY-----\n",
          "client_email": "notifier@inte-428705.iam.gserviceaccount.com",
          "client_id": "112405157857361091396",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/notifier%40inte-428705.iam.gserviceaccount.com",
          "universe_domain": "googleapis.com"
        }'
      run: |
        echo "$SERVICE_ACCOUNT_JSON" > /tmp/service_account.json
        python your_script.py
